<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="style.css">
    <title>Webber</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<header>
    <img src="CompanyLogo.png" alt="Creative Digital Media Agency logo" height="300" width="400">

    <nav>
        <a href="index.php">Home Page</a>
        <a href="jobs.php">Job Descriptions</a>
        <a href="apply.php">Apply to Us</a>
        <a href="about.php">About Us</a>
    </nav>
</header>